global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: inventory-server
    static_configs:
      - targets: ['inventory-server:3001']
    metrics_path: /metrics

  - job_name: server-manager
    static_configs:
      - targets: ['server-manager:3002']
    metrics_path: /metrics
